### ISSUE TITLE
Add cpp-ethereum to the list of clients

### ISSUE THREAD

**Issue by karalabe** [karalabe/hive#6]

**Comment by EtherTyper** [comment]
Should probably wait for 1.3.1 when Travis CI build workflow is finalized.

**Comment by karalabe** [comment]
I've added a Docker image that builds cpp-ethereum on Alpine. It's quite huge currently due to the gazillion dependencies but it's a starting point. The config/startup script still needs to be written though.

**Comment by holiman** [comment]
close me
